# Generated by Django 4.0.3 on 2024-01-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.TextField(max_length=200)),
                ('style_name', models.TextField(max_length=200)),
                ('color', models.TextField(max_length=200)),
                ('picture', models.URLField()),
            ],
        ),
    ]
