# Generated by Django 4.0.3 on 2024-01-31 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_alter_binvo_closet_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoe',
            options={'ordering': ('manufacturer', 'model_name', 'color', 'picture_url')},
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='bin',
        ),
    ]
