# Generated by Django 4.0.3 on 2024-01-31 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0003_alter_shoe_options_remove_shoe_bin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoe',
            options={},
        ),
    ]
