# Generated by Django 4.0.3 on 2024-02-01 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0004_alter_shoe_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binvo',
            name='import_href',
        ),
        migrations.AddField(
            model_name='binvo',
            name='bin_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binvo',
            name='bin_size',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binvo',
            name='reference_href',
            field=models.URLField(default='/api/shoes/1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='bin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='shoes_rest.binvo'),
            preserve_default=False,
        ),
    ]
